### ISSUE TITLE
BIG PROBLEM, MUST FIX IMMEDIATELY

### ISSUE THREAD

**Issue by rejhaa** [kallekankaanpaa/filterMap#1]
In the tests.ts, there is a big issue.
`const animals = ["crow", "cat", "dog", "lion", "cow", "pidgeon"];`
Animal referring to a bird (in the picture) is mispelled. 
![image](https://user-images.githubusercontent.com/16275630/187524956-a2ef4bcc-66ed-4096-891d-01bf6188c35e.png)
I believe it should be "pigeon" instead of pidgeon

Also later there is the same typo in:
`assert.deepEqual(result, ["CROW", "CAT", "DOG", "LION", "COW", "PIDGEON"]);`

Apparently "pidgeon" is "a surname from an archaic spelling of pigeon." But I don't believe the author was meaning this.

PLEASE FIX; MISSION CRITICAL

**Comment by kallekankaanpaa** [comment]
Thanks for the good first issue! Fixed the problem in [91290dfd4e39037d90b82851deb7a314580e0fc8](https://github.com/kallekankaanpaa/filterMap/commit/91290dfd4e39037d90b82851deb7a314580e0fc8)
